### ISSUE TITLE
a question about this port

### ISSUE THREAD

**Issue by Aliazzzz** [stefandreyer/OSCAT-BASIC#1]
There is a .package available via Codesys store for the OSCAT Basic (network & building) version.
So, what is your reason to port this (these) library (libraries) yourself?
Could/would you you elaborate on this?

Thank you, and with kind regards.

(bump)

**Comment by stefandreyer** [comment]
Hi Aliazzzz,

in fact, I dont't know/remeber. I have done this when I started to play and work with codesys. Maybe this time a newer version of the OSCAT library was not avalible in the store. 
But after i have done that, I used to work with them. 
So maybe if there are the next release of a library is published at oscat.de I'll do this again.

BR Stefan
